# ==============================================================================
# Astral Draft v4 - Production Prometheus Configuration
# ==============================================================================
# This configuration sets up comprehensive monitoring for the Astral Draft v4
# production environment with proper security, alerting, and data retention.
# ==============================================================================

global:
  # How frequently to scrape targets by default
  scrape_interval: 15s
  
  # How long until a scrape request times out
  scrape_timeout: 10s
  
  # How frequently to evaluate rules
  evaluation_interval: 15s
  
  # Attach these labels to any time series or alerts when communicating
  # with external systems (federation, remote storage, Alertmanager)
  external_labels:
    cluster: 'astral-draft-v4-production'
    environment: 'production'
    region: 'us-east-1'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'
      timeout: 10s
      api_version: v2

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  - "/etc/prometheus/rules/*.yml"

# ==============================================================================
# Scrape Configurations
# ==============================================================================

scrape_configs:
  # ========================================================================
  # Application Monitoring
  # ========================================================================
  
  # Next.js Application Metrics
  - job_name: 'astral-draft-app'
    static_configs:
      - targets: 
        - 'app-blue:3000'
        - 'app-green:3000'
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    params:
      format: ['prometheus']
    basic_auth:
      username: 'prometheus'
      password_file: '/etc/prometheus/secrets/app_metrics_password'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        regex: '.*-(.*):'
        target_label: deployment_slot
        replacement: '${1}'

  # API Health Checks
  - job_name: 'astral-draft-health'
    static_configs:
      - targets:
        - 'app-blue:3000'
        - 'app-green:3000'
    metrics_path: '/api/health'
    scrape_interval: 30s
    scrape_timeout: 10s
    scheme: http

  # ========================================================================
  # Infrastructure Monitoring
  # ========================================================================
  
  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - 'node-exporter:9100'
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'node-exporter:9100'

  # Docker Container Metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets:
        - 'cadvisor:8080'
    scrape_interval: 15s
    metrics_path: '/metrics'

  # ========================================================================
  # Database Monitoring
  # ========================================================================
  
  # PostgreSQL Metrics
  - job_name: 'postgres-exporter'
    static_configs:
      - targets:
        - 'postgres-exporter:9187'
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: database_role
        replacement: 'master'

  # PostgreSQL Replica Metrics (if available)
  - job_name: 'postgres-replica-exporter'
    static_configs:
      - targets:
        - 'postgres-replica-exporter:9187'
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: database_role
        replacement: 'replica'

  # ========================================================================
  # Cache and Session Store Monitoring
  # ========================================================================
  
  # Redis Metrics
  - job_name: 'redis-exporter'
    static_configs:
      - targets:
        - 'redis-exporter:9121'
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        target_label: redis_role
        replacement: 'master'

  # Redis Sentinel Metrics (if available)
  - job_name: 'redis-sentinel-exporter'
    static_configs:
      - targets:
        - 'redis-sentinel-exporter:9355'
    scrape_interval: 30s

  # ========================================================================
  # Load Balancer and Proxy Monitoring
  # ========================================================================
  
  # Nginx Metrics
  - job_name: 'nginx-exporter'
    static_configs:
      - targets:
        - 'nginx-exporter:9113'
    scrape_interval: 15s
    metrics_path: '/metrics'

  # ========================================================================
  # External Service Monitoring
  # ========================================================================
  
  # Blackbox Exporter for External Service Monitoring
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://astraldraft.com
        - https://astraldraft.com/api/health
        - https://api.sportsdata.io/v3/nfl/scores/json/CurrentSeason
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'

  # SSL Certificate Expiry Monitoring
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - astraldraft.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'blackbox-exporter:9115'

  # ========================================================================
  # Business Metrics
  # ========================================================================
  
  # Custom Business Metrics from Application
  - job_name: 'astral-draft-business'
    static_configs:
      - targets:
        - 'app-blue:3000'
        - 'app-green:3000'
    metrics_path: '/api/metrics/business'
    scrape_interval: 30s
    params:
      format: ['prometheus']
    basic_auth:
      username: 'prometheus'
      password_file: '/etc/prometheus/secrets/business_metrics_password'

  # ========================================================================
  # Prometheus Self-Monitoring
  # ========================================================================
  
  # Prometheus Server Metrics
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
    scrape_interval: 15s

  # Alertmanager Metrics
  - job_name: 'alertmanager'
    static_configs:
      - targets:
        - 'alertmanager:9093'
    scrape_interval: 15s

# ==============================================================================
# Remote Write Configuration (for Long-term Storage)
# ==============================================================================

# Uncomment and configure for remote storage (e.g., Cortex, Thanos, etc.)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password_file: "/etc/prometheus/secrets/remote_write_password"
#     queue_config:
#       capacity: 10000
#       max_shards: 200
#       min_shards: 1
#       max_samples_per_send: 5000
#       batch_send_deadline: 5s
#       min_backoff: 30ms
#       max_backoff: 100ms

# ==============================================================================
# Storage Configuration
# ==============================================================================

# Local storage configuration
storage:
  tsdb:
    # Retention period for metrics data
    retention.time: 30d
    
    # Maximum size of the storage
    retention.size: 50GB
    
    # Compression for better storage efficiency
    wal-compression: true
    
    # Block duration
    min-block-duration: 2h
    max-block-duration: 25h

# ==============================================================================
# Server Configuration
# ==============================================================================

# Web server configuration
web:
  # Listen address
  listen-address: '0.0.0.0:9090'
  
  # Path prefix for web console
  route-prefix: '/'
  
  # External URL
  external-url: 'https://prometheus.astraldraft.com'
  
  # Enable admin API
  enable-admin-api: true
  
  # Enable lifecycle API
  enable-lifecycle: true